### ISSUE TITLE
Add validation for environment variables

### ISSUE THREAD

**Issue by TanishqSingla** [TeamShiksha/logoexecutive#21]
## Overview
To add validation for environment variables used in the app.

## Problem Statement
Whenever we deploy or run the project locally there is no script to validate the setup.

## Proposed Solution
A validation step for environment variable should run against a validation schema. This will help us in:
- Ensuring developers environment variables are consistent and set properly
- Maintain non-ambiguity between development and production enviroment.

***Tasks for the project***

1) [x] - Create validation schema for environment variables
2) [x] - Add validation step before running the application
Or
2) [ ] - Add a script to ensure environment variables are set poperly
